### ISSUE TITLE
deepdream_visualization error: invalid reduction dimension

### ISSUE THREAD

**Issue by pabucur** [InFoCusp/tf_cnnvis#15]
When I call the `deepdream_visualization` function in the following way for MNIST classification,
```
random_representation = mnist_data.test.next_batch(1)
ran_x = preprocess_batch(random_representation[0], mean, std)
ran_y = random_representation[1]
feed_dict = {x: ran_x, y: ran_y, is_training: False, keep_probability: 1}
deep_dream = True
if deep_dream:
        layer = 'Conv/convolution'
        start = time.time()
        deepdream_visualization(graph_or_path=tf.get_default_graph(), value_feed_dict=feed_dict, layer=layer,
                                classes=[1, 2, 3, 4, 5, 6, 7, 8, 9],
                                input_tensor=None,
                                path_logdir="C:/Users/bucpau/PycharmProjects/Academy/Logs/",
                                path_outdir="C:/Users/bucpau/PycharmProjects/Academy/Visualization/")
        start = time.time() - start
        print("Total time for deconvolution visualization: {} Success: {}".format(start, is_success))
```
I get an error:
`Traceback (most recent call last):
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 156, in <module>
    main()
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 153, in main
    visualize_layers(test_dict)
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 85, in visualize_layers
    path_outdir="C:/Users/bucpau/PycharmProjects/Academy/Visualization/")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 393, in deepdream_visualization
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 138, in _get_visualization
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 264, in _visualization_by_layer_name
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 317, in _deepdream
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1382, in reduce_mean
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1364, in _mean
    keep_dims=keep_dims, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for 'Mean_1' (op: 'Mean') with input shapes: [?,784], [3] and with computed input tensors: input[1] = <1 2 3>.
`.

Any ideas on what is happening here? Is it a bug or am I using the function incorrectly? The activation visualization works, but the deconvolution does not with the input `feed_dict`. The only addition to this function call in comparison to the activation visualization are the parameters `classes` and `layer`. Am I setting them correctly?

**Comment by falaktheoptimist** [comment]
Hi!
If you're using CNN, then you must be reshaping the 784x1 image into 28x28 at some point. Could you pass in the tensor where this reshaped version is stored as the `input_tensor` argument into the `deepdream_visualization` function? That should resolve your issue. Same thing should also work for `deconvolution` function too. Parallely, we'll also try and get this to work for the flattened input case.
Let us know if you face any further issues.
Thanks!

**Comment by BhagyeshVikani** [comment]
Hello @pabucur,

Does your issue resolved by above suggested solution?

**Comment by pabucur** [comment]
@falaktheoptimist Thank you for the quick reply. Passing the image as 28x28 solves for me the deconvolution issue, but not the deepdream visualization. I then obtain a new error in the deepdream visualization, namely 
```
Traceback (most recent call last):
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 170, in <module>
    main()
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 167, in main
    visualize_layers(test_dict)
  File "C:/Users/bucpau/PycharmProjects/Academy/CNN_MNIST.py", line 89, in visualize_layers
    path_outdir=visualization_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 393, in deepdream_visualization
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 138, in _get_visualization
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 264, in _visualization_by_layer_name
  File "C:\ProgramData\Anaconda3\lib\site-packages\tf_cnnvis-1.0.0-py3.6.egg\tf_cnnvis\tf_cnnvis.py", line 355, in _deepdream
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 1397, in roll
    indexes = concatenate((arange(n - shift, n), arange(n - shift)))
TypeError: only length-1 arrays can be converted to Python scalars
```

The call to the deepdream visualization function was:
```
    deep_dream = True
    if deep_dream:
        layer = 'Conv/convolution'
        start = time.time()
        is_success = deepdream_visualization(graph_or_path=tf.get_default_graph(), value_feed_dict=feed_dict, layer=layer,
                                classes=[1, 2, 3, 4, 5, 6, 7, 8, 9],
                                input_tensor=None,
                                path_logdir=root_log_path,
                                path_outdir=visualization_path)
        start = time.time() - start
        print("Total time for deconvolution visualization: {} Success: {}".format(start, is_success))
```

My graph definition is as follows now:
```
def define_graph():
    graph = tf.Graph()
    with graph.as_default():
        x_2d = tf.placeholder(shape=(None, 28, 28, 1), dtype=tf.float32, name='x_2d')
        y = tf.placeholder(shape=(None, 10), dtype=tf.int32, name='y')
        keep_probability = tf.placeholder(tf.float32, name='keep_prob')
        is_training = tf.placeholder(tf.bool, name='is_training')

        conv_1 = slim.conv2d(inputs=x_2d, num_outputs=20, kernel_size=[5, 5])
        max_1 = slim.max_pool2d(inputs=conv_1, kernel_size=[2, 2])
        conv_2 = slim.conv2d(inputs=max_1, num_outputs=40, kernel_size=[5, 5])
        max_2 = slim.max_pool2d(inputs=conv_2, kernel_size=[2, 2])
        flattened = slim.flatten(max_2)
        fc_1 = slim.fully_connected(inputs=flattened, num_outputs=1000)
        drop_1 = slim.dropout(inputs=fc_1, keep_prob=keep_probability, is_training=is_training)
        fc_2 = slim.fully_connected(inputs=drop_1, num_outputs=1000)
        drop_2 = slim.dropout(inputs=fc_2, keep_prob=keep_probability, is_training=is_training)

        logits = slim.fully_connected(inputs=drop_2, num_outputs=10, activation_fn=None)
        cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=logits), name='cross_entropy')
        optimizer = tf.train.AdamOptimizer(learning_rate=0.00001)
        train_op = optimizer.minimize(cross_entropy, name='train_op')
        correctly_predicted = tf.equal(tf.argmax(y, 1), tf.argmax(logits, 1))
        accuracy = tf.reduce_mean(tf.cast(correctly_predicted, tf.float32), name='accuracy')
    return graph
```

**Comment by BhagyeshVikani** [comment]
Hi @pabucur ,

The below code works for us:
```
g = define_graph()

layer = 'Conv/convolution'
x_2d = g.get_tensor_by_name('x_2d:0')
y = g.get_tensor_by_name('y:0')
keep_probability = g.get_tensor_by_name('keep_prob:0')
is_training = g.get_tensor_by_name('is_training:0')

mnist_data = input_data.read_data_sets("MNIST_data/", one_hot=True)
random_representation = mnist_data.test.next_batch(1)
ran_x = random_representation[0].reshape((-1, 28, 28, 1)) / 255.0
ran_y = random_representation[1]
feed_dict = {x_2d: ran_x, y: ran_y, is_training: False, keep_probability: 1}

is_success = deepdream_visualization(graph_or_path=g, value_feed_dict=feed_dict, layer=layer,
                        classes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                        input_tensor=None,
                        path_logdir='/tmp/Log',
                        path_outdir='/tmp/Output')
```

Try this out.
Thank You

**Comment by pabucur** [comment]
Hi @BhagyeshVikani : I copy-pasted your code at the end of the training phase, switching only the path of the `logdir` and the `outdir`. I still have the same error. Can you maybe post your full MNIST working code as an example (or here if you prefer)? Thank you.

**Comment by BhagyeshVikani** [comment]
Hello @pabucur,

Below is our full code:
```
# imports
import sys
import time
import numpy as np
from tf_cnnvis import *
import tensorflow as tf
import tensorflow.contrib.slim as slim

from tensorflow.examples.tutorials.mnist import input_data

np.random.seed(10)

def define_graph():
    graph = tf.Graph()
    with graph.as_default():
        x_2d = tf.placeholder(shape=(None, 28, 28, 1), dtype=tf.float32, name='x_2d')
        y = tf.placeholder(shape=(None, 10), dtype=tf.int32, name='y')
        keep_probability = tf.placeholder(tf.float32, name='keep_prob')
        is_training = tf.placeholder(tf.bool, name='is_training')

        conv_1 = slim.conv2d(inputs=x_2d, num_outputs=20, kernel_size=[5, 5])
        max_1 = slim.max_pool2d(inputs=conv_1, kernel_size=[2, 2])
        conv_2 = slim.conv2d(inputs=max_1, num_outputs=40, kernel_size=[5, 5])
        max_2 = slim.max_pool2d(inputs=conv_2, kernel_size=[2, 2])
        flattened = slim.flatten(max_2)
        fc_1 = slim.fully_connected(inputs=flattened, num_outputs=1000)
        drop_1 = slim.dropout(inputs=fc_1, keep_prob=keep_probability, is_training=is_training)
        fc_2 = slim.fully_connected(inputs=drop_1, num_outputs=1000)
        drop_2 = slim.dropout(inputs=fc_2, keep_prob=keep_probability, is_training=is_training)

        logits = slim.fully_connected(inputs=drop_2, num_outputs=10, activation_fn=None)
        cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=logits), name='cross_entropy')
        optimizer = tf.train.AdamOptimizer(learning_rate=0.00001)
        train_op = optimizer.minimize(cross_entropy, name='train_op')
        correctly_predicted = tf.equal(tf.argmax(y, 1), tf.argmax(logits, 1))
        accuracy = tf.reduce_mean(tf.cast(correctly_predicted, tf.float32), name='accuracy')
    return graph

g = define_graph()

layer = 'Conv/convolution'
x_2d = g.get_tensor_by_name('x_2d:0')
y = g.get_tensor_by_name('y:0')
keep_probability = g.get_tensor_by_name('keep_prob:0')
is_training = g.get_tensor_by_name('is_training:0')

mnist_data = input_data.read_data_sets("MNIST_data/", one_hot=True)
random_representation = mnist_data.test.next_batch(1)
ran_x = random_representation[0].reshape((-1, 28, 28, 1)) / 255.0
ran_y = random_representation[1]
feed_dict = {x_2d: ran_x, y: ran_y, is_training: False, keep_probability: 1}

is_success = deepdream_visualization(graph_or_path=g, value_feed_dict=feed_dict, layer=layer,
                        classes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                        input_tensor=None,
                        path_logdir='/tmp/Log',
                        path_outdir='/tmp/Output')
                        
```

Try running this code as it is. And let us know the results.

Thank You.

**Comment by pabucur** [comment]
@BhagyeshVikani I posted the code into a new Python file, without changing anything. It does not work for me, the error is the same. I am on Windows 7 and using Tensorflow with GPU support, version 1.3.0-rc1.

**Comment by BhagyeshVikani** [comment]
Hii @pabucur,

We found the root cause of the error. `Numpy < 1.12` caused this issue since there was a change in the arguments that go into `np.roll` starting from `numpy==1.12`. But now we have updated `tf_cnnvis` to allow for backward compatibility with numpy.

Now `git pull tf_cnnvis`  and setup should resolve this issue. Thanks for taking the time to debug and point out this issue.

Thank You.
